name: Build

on: push

jobs:
  Linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6

      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install LibVLC and Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib install hxpkg
          haxelib run hxpkg setup
          hxpkg install

      - name: Set up HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Compile
        run: haxelib run lime build linux

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR (Linux)
          path: 'export/release/linux/bin'

  Windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6

      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib install hxpkg
          haxelib run hxpkg setup
          hxpkg install

      - name: Set up HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Compile
        run: haxelib run lime build windows

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR (Windows)
          path: export/release/windows/bin

  macOS:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6

      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib install hxpkg
          haxelib run hxpkg setup
          hxpkg install

      - name: Set up HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp/
          haxe compile.hxml
          cd ../../../../../

      - name: Compile
        run: arch -x86_64 haxelib run lime build mac

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR (macOS)
          path: export/release/macos/bin
